// Generated by the plugin protoc-gen-shmproto of protocol buffer compiler.  DO NOT EDIT!
//  source: hello.pb

#include <iostream>
#include "hello.pb.shm.hpp"
namespace helloworld
{
    static shm_proto::ShmProtoRegister<ShmHelloTestItem> instance_0;
    static shm_proto::ShmProtoRegister<ShmHelloTestData> instance_1;
}
